services:
  - type: web
    name: jose-caicedo-lab5-quote-finder
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
